version: '3'
services:
  app:
    container_name: go-web-mongo
    restart: always
    build: .
    ports:
      - '8082:8083'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'